# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: mini-test-app-v1 CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
          with:
               python-version: '3.8'  # Replace with the version you want

        - name: Install dependencies
          run: |
             python -m pip install --upgrade pip
             pip install -r requirements.txt

        - name: Run tests
          run: pytest

  build_windows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
            python-version: '3.12'  # Replace with the version you want
            
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest
